### ISSUE TITLE
sts_filterDatetime() is off by a minute with POSIXct date formats

### ISSUE THREAD

**Issue by EliGrosman** [MazamaScience/MazamaTimeSeries#5]
When given POSIXct date inputs, `sts_filterDate()` is off by a minute.

Example: 

```
> start_Hawaii <- ISOdatetime(2018, 08, 02, 00, 00, 00, tz = "US/Hawaii")
> end_Hawaii <- ISOdatetime(2018, 08, 02, 23, 59, 00, tz = "US/Hawaii")

> range( sts_filterDatetime(example_sts, start_Hawaii, end_Hawaii)$data$datetime )
[1] "2018-08-02 10:00:00 UTC" "2018-08-03 09:58:00 UTC"
```

Actual output should include 09:59:00 but cuts off early at 09:59:00.

**Comment by jonathancallahan** [comment]
Make sure that `example_sts` actually has a record in the 09:59:00 minute. It's possible that 09:58:00 is the last available record.
